export const GA_MAINTENANCE_REQUEST_CREATE = 'general_affairs.maintenance_request.create';
export const GA_MAINTENANCE_REQUEST_VIEW_OWN_STORE = 'general_affairs.maintenance_request.view_own_store';
export const GA_MAINTENANCE_REQUEST_VIEW_ALL = 'general_affairs.maintenance_request.view_all';
export const GA_MAINTENANCE_REQUEST_UPDATE = 'general_affairs.maintenance_request.update';

export const GA_WORK_ORDER_VIEW_OWN_STORE = 'general_affairs.work_order.view_own_store';
export const GA_WORK_ORDER_VIEW_ALL = 'general_affairs.work_order.view_all';
export const GA_WORK_ORDER_UPDATE = 'general_affairs.work_order.update';
export const GA_WORK_ORDER_MANAGE = 'general_affairs.work_order.manage';

export const GA_MAINTENANCE_REQUEST_CREATE_CODES = [
  GA_MAINTENANCE_REQUEST_CREATE,
  GA_MAINTENANCE_REQUEST_VIEW_ALL,
];

export const GA_MAINTENANCE_REQUEST_VIEW_CODES = [
  GA_MAINTENANCE_REQUEST_CREATE,
  GA_MAINTENANCE_REQUEST_VIEW_OWN_STORE,
  GA_MAINTENANCE_REQUEST_VIEW_ALL,
  GA_MAINTENANCE_REQUEST_UPDATE,
];

export const GA_MAINTENANCE_REQUEST_MANAGE_CODES = [
  GA_MAINTENANCE_REQUEST_VIEW_ALL,
  GA_MAINTENANCE_REQUEST_UPDATE,
];

export const GA_WORK_ORDER_VIEW_CODES = [
  GA_WORK_ORDER_VIEW_OWN_STORE,
  GA_WORK_ORDER_VIEW_ALL,
  GA_WORK_ORDER_UPDATE,
  GA_WORK_ORDER_MANAGE,
];

export const GA_WORK_ORDER_MANAGE_CODES = [
  GA_WORK_ORDER_UPDATE,
  GA_WORK_ORDER_MANAGE,
];

export const GA_MAINTENANCE_MODULE_CODES = [
  ...GA_MAINTENANCE_REQUEST_VIEW_CODES,
  ...GA_WORK_ORDER_VIEW_CODES,
];

export const GA_WORK_ORDER_MODULE_CODES = [
  ...GA_WORK_ORDER_VIEW_CODES,
  GA_MAINTENANCE_REQUEST_VIEW_ALL,
  GA_MAINTENANCE_REQUEST_UPDATE,
];

// Legacy cross-department maintenance permissions remain valid only for the
// legacy cross-department maintenance surface and shared legacy tables.
export const CROSS_DEPT_MAINTENANCE_SUBMIT = 'cross_dept.maintenance.submit';
export const CROSS_DEPT_MAINTENANCE_VIEW_ALL = 'cross_dept.maintenance.view_all';
export const CROSS_DEPT_MAINTENANCE_UPDATE = 'cross_dept.maintenance.update';
export const CROSS_DEPT_MAINTENANCE_CATEGORY_EDIT = 'cross_dept.maintenance.category.edit';

export const LEGACY_CROSS_DEPT_MAINTENANCE_VIEW_CODES = [
  CROSS_DEPT_MAINTENANCE_SUBMIT,
  CROSS_DEPT_MAINTENANCE_VIEW_ALL,
  CROSS_DEPT_MAINTENANCE_UPDATE,
];

export const SHARED_MAINTENANCE_REQUEST_CREATE_CODES = [
  ...GA_MAINTENANCE_REQUEST_CREATE_CODES,
  CROSS_DEPT_MAINTENANCE_SUBMIT,
  CROSS_DEPT_MAINTENANCE_VIEW_ALL,
];

export const SHARED_MAINTENANCE_REQUEST_VIEW_ALL_CODES = [
  GA_MAINTENANCE_REQUEST_VIEW_ALL,
  GA_MAINTENANCE_REQUEST_UPDATE,
  GA_WORK_ORDER_VIEW_ALL,
  GA_WORK_ORDER_UPDATE,
  GA_WORK_ORDER_MANAGE,
  CROSS_DEPT_MAINTENANCE_VIEW_ALL,
  CROSS_DEPT_MAINTENANCE_UPDATE,
];

export const SHARED_MAINTENANCE_REQUEST_UPDATE_CODES = [
  ...GA_MAINTENANCE_REQUEST_MANAGE_CODES,
  ...GA_WORK_ORDER_MANAGE_CODES,
  CROSS_DEPT_MAINTENANCE_VIEW_ALL,
  CROSS_DEPT_MAINTENANCE_UPDATE,
];

export const SHARED_MAINTENANCE_CATEGORY_VIEW_CODES = [
  ...GA_MAINTENANCE_MODULE_CODES,
  CROSS_DEPT_MAINTENANCE_SUBMIT,
  CROSS_DEPT_MAINTENANCE_VIEW_ALL,
  CROSS_DEPT_MAINTENANCE_UPDATE,
  CROSS_DEPT_MAINTENANCE_CATEGORY_EDIT,
];
